[package]
name = "evcxr_jupyter"
version = "0.12.0"
license = "Apache-2.0"
description = "An Jupyter Kernel for Rust"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = ["The Evcxr Authors"]
edition = "2018"

[dependencies]
evcxr = { version = "=0.12.0", path = "../evcxr" }
json = "0.12.4"
anyhow = "1.0.33"
zmq = { version = "0.9.1", default-features = false }
uuid = { version = "0.8.1", features = [ "v4" ] }
hmac = "0.11.0"
sha2 = "0.9.3"
hex = "0.4.2"
colored = "2.0.0"
dirs = "3.0.1"
chrono = "0.4.19"
unicode-segmentation = "1.7.1"
mimalloc = { version = "0.1", default-features = false, optional = true }

[features]
default = ["vendored-zmq", "mimalloc"]
vendored-zmq = ["zmq/vendored"]
