[package]
name = "evcxr_jupyter"
version = "0.4.3"
license = "Apache-2.0"
description = "An Jupyter Kernel for Rust"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = [
    "David Lattimore <dvdlttmr@gmail.com>",
    "David Bernard <david.bernard.31@gmail.com>",
]
edition = "2018"

[dependencies]
evcxr = { version = "=0.4.3", path = "../evcxr" }
json = "0.11.13"
failure = { version = "0.1.5", default-features = false, features = [ "std" ] }
zmq = "0.9.1"
uuid = { version = "0.7.2", features = [ "v4" ] }
hmac = "0.7.0"
sha2 = "0.8.0"
hex = "0.3.2"
colored = "1.8.0"
dirs = "2.0.1"
chrono = "0.4.6"
