dist: xenial
language: rust
matrix:
  include:
    - os: linux
      rust: 1.36.0
      env: TARGET=x86_64-unknown-linux-gnu EXTRA_ARGS=""
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu EXTRA_ARGS=""
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin EXTRA_ARGS=""
    - os: windows
      rust: beta
      env: TARGET=x86_64-pc-windows-msvc EXTRA_ARGS="--exclude=evcxr_jupyter"
  fast_finish: true

install:
  # prevent target re-add error from rustup
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TARGET" != "x86_64-unknown-linux-gnu" ]]; then rustup target add $TARGET; fi

before_script:
  - rustup -V; rustc -V; cargo -V
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then rm "C:/Program Files/Git/usr/bin/sh.exe"; fi

script:
  - travis_wait 30 cargo build --verbose --all $EXTRA_ARGS --all-features
  - travis_wait 30 cargo test --verbose --all $EXTRA_ARGS
  - cargo run -p print_performance_info

notifications:
  email:
    - dvdlttmr@gmail.com
