[package]
name = "evcxr"
version = "0.4.7"
license = "Apache-2.0"
description = "An Evaluation Context for Rust"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = [
    "David Lattimore <dvdlttmr@gmail.com>",
    "Matthias Bussonnier <bussonniermatthias@gmail.com>",
    "Daniel Griffen <daniel@griffen.io>",
    "David Bernard <david.bernard.31@gmail.com>",
]
edition = "2018"

[dependencies]
syn = { version = "1.0.11", default-features = false, features = ["parsing", "full", "printing", "clone-impls", "extra-traits", "visit"] }
proc-macro2 = { version = "1.0.6", default-features = false }
failure = { version = "0.1.5", default-features = false, features = [ "std" ] }
tempfile = "3.1.0"
libc = "0.2.62"
json = "0.11.15"
regex = { version = "1.3.1", default-features = false, features = [ "std" ] }
lazy_static = "1.3.0"
libloading = "0.5.2"
backtrace = "0.3.35"
dirs = "2.0.2"
which = "2.0.1"

[target.'cfg(unix)'.dependencies]
sig = "1.0.0"
