[package]
name = "evcxr_runtime"
version = "1.0.0"
license = "Apache-2.0"
description = "Runtime core for the evcxr crate"
repository = "https://github.com/google/evcxr"
readme = "README.md"
authors = ["David Lattimore <dml@google.com>"]

[dependencies]
base64 = "0.9.3"
