[package]
name = "evcxr_input"
version = "1.0.0"
license = "MIT OR Apache-2.0"
description = "Support for reading input from the user in Evcxr"
repository = "https://github.com/evcxr/evcxr"
authors = ["The Evcxr Authors"]
edition = "2024"

[dependencies]
