[package]
name = "evcxr_input"
version = "1.0.0"
license = "Apache-2.0"
description = "Support for reading input from the user in Evcxr"
repository = "https://github.com/google/evcxr"
authors = ["The Evcxr Authors"]
edition = "2021"

[dependencies]
